name: Test

# on:
#     push:
#         branches: ["master"]

# on: push

on: 
  schedule:
    - cron: '54 18 * * *'

jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Built it!
      run: echo 'Hello World'
    